# Generated by Django 4.1.3 on 2023-01-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
