# Generated by Django 4.1.3 on 2023-01-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fishermen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=200)),
                ('Vname', models.CharField(max_length=200)),
                ('Fphone', models.IntegerField()),
                ('Faddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marina_officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oname', models.CharField(max_length=200)),
                ('Oaddress', models.CharField(max_length=200)),
                ('Mname', models.CharField(max_length=200)),
                ('Ophone', models.IntegerField()),
            ],
        ),
    ]
